<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [ ]:
import numpy as np

In [8]:
array_secuencial = np.arange(10)
array_secuencial

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [10]:
print(array_secuencial.shape)
array_secuencial_reshaped = np.reshape(array_secuencial,(2,5))
print(array_secuencial_reshaped.shape)

(10,)
(2, 5)


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [29]:
arr = np.array([0, 2, 0, 3, 0, 4, 0])

value = 0
print(np.where(arr != value))

(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [ ]:
print(np.random.rand(3,3))

[[0.66048487 0.39881293 0.65999344]
 [0.03923397 0.08116208 0.5280073 ]
 [0.67660447 0.12054756 0.95696741]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [32]:
rand_arr = np.random.randint(0, 101, 10)
min_value = np.min(rand_arr)
max_value = np.max(rand_arr)

print("Array:", rand_arr)
print("Valor máximo", max_value)
print("Valor mínimo:", min_value)

Array: [44 33 12  0 51 53 69 28 79 71]
Valor máximo 79
Valor mínimo: 0


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [37]:
inverted_rand_arr = np.flip(rand_arr)
inverted_rand_arr

array([71, 79, 28, 69, 53, 51,  0, 12, 33, 44])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [54]:
arr_3d = np.arange(1, 25).reshape(2, 3, 4)

coordenadas = np.argwhere(arr_3d == 15)
primera_coordenada = coordenadas[0]

primer_array = arr_3d[0]

ultima_fila_ultimo_array = arr_3d[-1, -1]

print(arr_3d)
print("Posición primer 15:", primera_coordenada)
print("Primer array:")
print(primer_array)
print("Última fila del último array:")
print(ultima_fila_ultimo_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Posición primer 15: [1 0 2]
Primer array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Última fila del último array:
[21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


Array tridimensional:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]

Subarray del primer array (dos primeros elementos de cada fila):
[[1 2]
 [6 7]]

Subarray de los dos últimos arrays (todas las filas):
[[[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [11]:
import numpy as np

# Crear un array tridimensional con dimensiones (3, 4, 5) y valores aleatorios entre -10 y 10
array_3d = np.random.randint(-10, 11, (3, 4, 5))

# Crear un array vacío con la misma forma
array_empty = np.empty_like(array_3d, dtype=object)

# Calcular los valores de la mediana, máximo y mínimo
median_value = np.median(array_3d)
max_value = np.max(array_3d)
min_value = np.min(array_3d)

# Reemplazar los valores en el array vacío según las condiciones
for index, value in np.ndenumerate(array_3d):
    if value == median_value:
        array_empty[index] = "M"
    elif value > median_value:
        array_empty[index] = "X"
    elif value < median_value:
        array_empty[index] = "Y"
    if value == max_value:
        array_empty[index] = "MAX"
    elif value == min_value:
        array_empty[index] = "MIN"

# Mostrar el resultado
print("Array original (3D):")
print(array_3d)
print("\nArray modificado (con las condiciones):")
print(array_empty)


Array original (3D):
[[[-10  10  -2  10   4]
  [ -7   3  -8 -10  10]
  [ -2   2  -4  10  -3]
  [ -5   4   7   7   7]]

 [[  3  -6  -1  10   5]
  [ -7   3  -5 -10  -1]
  [  8   1   1   5   1]
  [ -4  10  -3   6  -4]]

 [[  7  -4   8   8   0]
  [ 10   0  -5  -3   3]
  [  4   8  -7   3   2]
  [  5 -10   1   0  -5]]]

Array modificado (con las condiciones):
[[['MIN' 'MAX' 'Y' 'MAX' 'X']
  ['Y' 'X' 'Y' 'MIN' 'MAX']
  ['Y' 'X' 'Y' 'MAX' 'Y']
  ['Y' 'X' 'X' 'X' 'X']]

 [['X' 'Y' 'Y' 'MAX' 'X']
  ['Y' 'X' 'Y' 'MIN' 'Y']
  ['X' 'M' 'M' 'X' 'M']
  ['Y' 'MAX' 'Y' 'X' 'Y']]

 [['X' 'Y' 'X' 'X' 'Y']
  ['MAX' 'Y' 'Y' 'Y' 'X']
  ['X' 'X' 'Y' 'X' 'X']
  ['X' 'MIN' 'M' 'Y' 'Y']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.